	compression u0 (
		.clk_clk          (<connected-to-clk_clk>),          //       clk.clk
		.leds_w_export    (<connected-to-leds_w_export>),    //    leds_w.export
		.line1_1_in_port  (<connected-to-line1_1_in_port>),  //   line1_1.in_port
		.line1_1_out_port (<connected-to-line1_1_out_port>), //          .out_port
		.line1_2_in_port  (<connected-to-line1_2_in_port>),  //   line1_2.in_port
		.line1_2_out_port (<connected-to-line1_2_out_port>), //          .out_port
		.line2_1_in_port  (<connected-to-line2_1_in_port>),  //   line2_1.in_port
		.line2_1_out_port (<connected-to-line2_1_out_port>), //          .out_port
		.line2_2_in_port  (<connected-to-line2_2_in_port>),  //   line2_2.in_port
		.line2_2_out_port (<connected-to-line2_2_out_port>), //          .out_port
		.line3_1_in_port  (<connected-to-line3_1_in_port>),  //   line3_1.in_port
		.line3_1_out_port (<connected-to-line3_1_out_port>), //          .out_port
		.line3_2_in_port  (<connected-to-line3_2_in_port>),  //   line3_2.in_port
		.line3_2_out_port (<connected-to-line3_2_out_port>), //          .out_port
		.line4_1_in_port  (<connected-to-line4_1_in_port>),  //   line4_1.in_port
		.line4_1_out_port (<connected-to-line4_1_out_port>), //          .out_port
		.line4_2_in_port  (<connected-to-line4_2_in_port>),  //   line4_2.in_port
		.line4_2_out_port (<connected-to-line4_2_out_port>), //          .out_port
		.line5_1_in_port  (<connected-to-line5_1_in_port>),  //   line5_1.in_port
		.line5_1_out_port (<connected-to-line5_1_out_port>), //          .out_port
		.line5_2_in_port  (<connected-to-line5_2_in_port>),  //   line5_2.in_port
		.line5_2_out_port (<connected-to-line5_2_out_port>), //          .out_port
		.line6_1_in_port  (<connected-to-line6_1_in_port>),  //   line6_1.in_port
		.line6_1_out_port (<connected-to-line6_1_out_port>), //          .out_port
		.line6_2_in_port  (<connected-to-line6_2_in_port>),  //   line6_2.in_port
		.line6_2_out_port (<connected-to-line6_2_out_port>), //          .out_port
		.line7_1_in_port  (<connected-to-line7_1_in_port>),  //   line7_1.in_port
		.line7_1_out_port (<connected-to-line7_1_out_port>), //          .out_port
		.line7_2_in_port  (<connected-to-line7_2_in_port>),  //   line7_2.in_port
		.line7_2_out_port (<connected-to-line7_2_out_port>), //          .out_port
		.line8_1_in_port  (<connected-to-line8_1_in_port>),  //   line8_1.in_port
		.line8_1_out_port (<connected-to-line8_1_out_port>), //          .out_port
		.line8_2_in_port  (<connected-to-line8_2_in_port>),  //   line8_2.in_port
		.line8_2_out_port (<connected-to-line8_2_out_port>), //          .out_port
		.reset_reset_n    (<connected-to-reset_reset_n>),    //     reset.reset_n
		.sdram_addr       (<connected-to-sdram_addr>),       //     sdram.addr
		.sdram_ba         (<connected-to-sdram_ba>),         //          .ba
		.sdram_cas_n      (<connected-to-sdram_cas_n>),      //          .cas_n
		.sdram_cke        (<connected-to-sdram_cke>),        //          .cke
		.sdram_cs_n       (<connected-to-sdram_cs_n>),       //          .cs_n
		.sdram_dq         (<connected-to-sdram_dq>),         //          .dq
		.sdram_dqm        (<connected-to-sdram_dqm>),        //          .dqm
		.sdram_ras_n      (<connected-to-sdram_ras_n>),      //          .ras_n
		.sdram_we_n       (<connected-to-sdram_we_n>),       //          .we_n
		.sdram_pll_clk    (<connected-to-sdram_pll_clk>)     // sdram_pll.clk
	);

